### ISSUE TITLE
Unable to download the packages from mvn clean install

### ISSUE THREAD

**Issue by vijayendra-prabhakar** [omoponfhir/omoponfhir-main-r4-sql#1]
During the initial setups while downloading the dependencies, I get an error saying

[ERROR] Failed to execute goal on project omoponfhir-omopv5-sql: Could not resolve dependencies for project edu.gatech.chai:omoponfhir-omopv5-sql:jar:1.3.0: Failed to collect dependencies at org.ohdsi.sql:SqlRender:jar:1.6.4: Failed to read artifact descriptor for org.ohdsi.sql:SqlRender:jar:1.6.4: Could not transfer artifact org.ohdsi.sql:SqlRender:pom:1.6.4 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [ohdsi (http://repo.ohdsi.org:8085/nexus/content/repositories/releases, default, releases+snapshots), ohdsi.snapshots (http://repo.ohdsi.org:8085/nexus/content/repositories/snapshots, default, snapshots)] -> [Help 1
![OHDSIError](https://user-images.githubusercontent.com/6717368/160588127-12528669-effa-4814-a627-a97656ab8bd0.png)
]

**Comment by myungchoi** [comment]
The SQLRender repo is managed by OHDSI group. The server may be down at the
moment. Please try again later. If problem persists, you need to contact
OHDSI.

**Comment by myungchoi** [comment]
Found why it happens. Maven no longer allows http://. Changing this to https:// in the pom file make this working

**Comment by jdamato-mitre** [comment]
Was this change ever committed to the repo? What pom file does this need to be changed in?
