### ISSUE TITLE
Using schema other than `public` in PostgreSQL

### ISSUE THREAD

**Issue by paulstey** [omoponfhir/omoponfhir-main-r4-sql#10]
Thanks so much for your work on this,@myungchoi!! 

I was wondering if it's possible to use a schema _other than_ the `public` schema when using PostgreSQL. [The DDL for Postgres](https://github.com/omoponfhir/omoponfhir-main-r4-sql/blob/main/omopv5_3_setup/CommonDataModel/PostgreSQL/OMOP%20CDM%20postgresql%20ddl.txt) seems to put all tables in the default (i.e., `public`) schema. 

For example, if I have my data in a schema called `cdm` and my vocabularies in a `vocab` schema, would that work? I don't see any configuration fields or environment variables that would all us to modify the schemas to be use. Do there need to be changes to the Java code to accommodate this? 

Again, thank you so much for your work on this, Myung!

**Comment by myungchoi** [comment]
You can change the schema name. Currently, both cdm and vocab need to be in the same schema. I have another OMOPonFHIR implementation that I am using as a registry. That has the capability that you want (using cdm from one schema and vocabulary from another schema). I haven't had a chance to apply the changes to this code stack. I will see if I can do. Until then, your vocab needs to be in the same schema. And, the schema name can be specified in the JDBC_URL environment valuable by adding "currentSchema" URL parameter.

**Comment by paulstey** [comment]
Thanks so much for following up, Myung! That all sounds great! 

Thanks again for all your work on this, @myungchoi!!!
