### ISSUE TITLE
Docker image do not work on M1 macs

### ISSUE THREAD

**Issue by rdingwell** [omoponfhir/omoponfhir-main-r4-sql#2]
The docker build does not work on apple silicone.  This is related to using alpine images as a base.  The main issue ends up being SQLite native library support for those images.  Switching the build image to maven and the runtime image to tomcat:9.0 resolves the issue.  I would not think that this would cause problems on intel based systems.

**Comment by myungchoi** [comment]
> The docker build does not work on apple silicone. This is related to using alpine images as a base. The main issue ends up being SQLite native library support for those images. Switching the build image to maven and the runtime image to tomcat:9.0 resolves the issue. I would not think that this would cause problems on intel based systems.

Yes, the JDBC sqlite driver did not support the M1 chip Mac. The fix was applied to the mapping stack. But, haven't been applied to this deployment repo. Updated all changes made so far. Thank you for letting us know.
