### ISSUE TITLE
Trouble when deploying with Docker

### ISSUE THREAD

**Issue by alexdefelipe** [omoponfhir/omoponfhir-main-r4-sql#4]
Hi!

I'm having trouble when deploying omoponfhir with Docker.

The problem is that, in the `omoponfhir-omopv5-r4-mapping` project, [the method String.isBlank()](https://github.com/omoponfhir/omoponfhir-omopv5-r4-mapping/commit/04d7ec04da41133bf3f4be14fcd6c1843d3e5e68), [which has been in Java JDK since version 11](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#isBlank()), is beeing used, but the Dockerfile in this project is based on [Maven 3.6.1-alpine](https://hub.docker.com/layers/library/maven/3.6.1-alpine/images/sha256-7445f83cd169b9f0b185e443e755ece1e37d3cf1e2e90f9180afad2fdb9d2bc4?context=explore) image, which has got Java 8 installed. So when compiling it can't find that method.

Thank you!

**Comment by myungchoi** [comment]
Just updated the Dockerfile to use Java 17 for maven build and tomcat. Please let us know if the issue persists.
